# Generated by Django 4.1.2 on 2022-10-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_seller'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cart',
        ),
        migrations.AddField(
            model_name='profile',
            name='cart',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
