# Generated by Django 4.1.2 on 2022-10-21 15:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interested_users', models.ManyToManyField(related_name='added_to_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
