# Generated by Django 4.1.2 on 2022-10-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discription',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
