# Generated by Django 4.1.2 on 2022-10-21 07:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='interested_users',
            field=models.ManyToManyField(related_name='followed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
