# Generated by Django 4.1.2 on 2022-10-24 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_cart_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cart_flag',
        ),
    ]
